name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP
  run: |
    net user runneradmin Passw0rd!

    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

    - name: Start RDP Tunnel
      run: |
        .\ngrok.exe tcp 3389
